import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://tecyad.ir';

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/courses',
          '/courses/*',
          '/classes',
          '/classes/*',
          '/instructors',
          '/instructors/*',
          '/blog',
          '/blog/*',
          '/about',
          '/contact',
          '/faq',
          '/rules',
          '/privacy',
          '/careers',
          '/search',
        ],
        disallow: [
          '/student/',
          '/student/*',
          '/instructor/',
          '/instructor/*',
          '/admin/',
          '/admin/*',
          '/super-admin/',
          '/super-admin/*',
          '/payment/',
          '/payment/*',
          '/cart',
          '/checkout',
          '/profile',
          '/login',
          '/register',
          '/forgot-password',
          '/reset-password',
          '/api/',
          '/api/*',
          '/*?*sort=',
          '/*?*filter=',
          '/*?*price=',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/student/',
          '/instructor/',
          '/admin/',
          '/super-admin/',
          '/payment/',
          '/cart',
          '/checkout',
          '/profile',
          '/login',
          '/register',
          '/forgot-password',
          '/reset-password',
          '/api/',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
